"""Initial migration

Revision ID: e384b5254f23
Revises:
Create Date: 2025-04-02 13:56:17.423837

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e384b5254f23"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "baskets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mushrooms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("edible", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("fresh", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "basket_mushrooms",
        sa.Column("basket_id", sa.UUID(), nullable=False),
        sa.Column("mushroom_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["basket_id"], ["baskets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mushroom_id"], ["mushrooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("basket_id", "mushroom_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("basket_mushrooms")
    op.drop_table("mushrooms")
    op.drop_table("baskets")
    # ### end Alembic commands ###
